<x-layout>
    <x-slot:title>{{ $title }}</x-slot:title>
    <main class="max-w-6xl mx-auto px-4 py-8">
        <h1 class="text-2xl font-semibold text-center mb-8">Produk Kami</h1>
        
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mb-10">
            <!-- Product -->
            @foreach($products as $product)
            <div class="bg-white rounded-lg overflow-hidden shadow hover:-translate-y-1 transition-transform duration-300 p-2">
                <div class="h-44 overflow-hidden">
                    <img src="{{ asset('storage/product/'. $product->imgname) }}" alt="Rendang Daging Sapi" class="w-full h-full rounded-[6px] object-cover">
                </div>
                <div class="p-4">
                    <h3 class="font-semibold mb-1">{{ $product->nama }}</h3>
                    <p class="text-sm text-gray-600 mb-1">{{ $product->deskripsi }}</p>
                    <p class="font-semibold mb-3">Rp. {{ number_format($product->harga,0,',','.') }}</p>
                    <button class="cursor-pointer w-full py-2 border border-[#ff9a00] text-[#ff9a00] hover:bg-[#ff9a00] hover:text-white transition-colors rounded font-medium add-to-cart" data-productid = {{ $product->product_id }}>
                        Add to Cart
                    </button>
                </div>
            </div>
            @endforeach
        </div>
        
        <div class="max-w-lg mx-auto bg-white rounded-lg shadow p-6">
            <h2 class="bg-[#ff9a00] text-white text-center py-3 rounded-t-lg font-semibold -mx-6 -mt-6 mb-6">Jadwal Pengiriman Catering</h2>
            
            <div class="mb-4">
                <label for="delivery-date" class="block mb-1 font-medium">Tanggal Pengiriman</label>
                <input type="text" id="delivery-date" class="w-full p-2 border border-gray-200 rounded" value="20 Juni 2025" readonly>
            </div>
            
            <div class="mb-4">
                <div class="bg-white border border-gray-200 rounded">
                    <div class="bg-[#ff9a00] text-white px-4 py-2 flex justify-between items-center rounded-t">
                        <button id="prev-month" class="text-white cursor-pointer">&lt;</button>
                        <div id="calendar-month" class="font-semibold">Juni 2025</div>
                        <button id="next-month" class="text-white cursor-pointer">&gt;</button>
                    </div>
                    
                    <div class="grid grid-cols-7 gap-1 p-2" id="calendar-grid">
                        <div class="text-center p-1 text-sm font-medium">Sen</div>
                        <div class="text-center p-1 text-sm font-medium">Sel</div>
                        <div class="text-center p-1 text-sm font-medium">Rab</div>
                        <div class="text-center p-1 text-sm font-medium">Kam</div>
                        <div class="text-center p-1 text-sm font-medium">Jum</div>
                        <div class="text-center p-1 text-sm font-medium">Sab</div>
                        <div class="text-center p-1 text-sm font-medium">Min</div>
                        <!-- Calendar days will be generated by JavaScript -->
                    </div>
                </div>
            </div>
            
            <div class="mb-4">
                <label for="delivery-time" class="block mb-1 font-medium">Waktu Pengiriman</label>
                <input type="time" id="delivery-time" class="w-full p-2 border border-gray-200 rounded">
            </div>
            
            <div class="mb-4">
                <label for="delivery-address" class="block mb-1 font-medium">Alamat Pengiriman</label>
                <textarea id="delivery-address" class="w-full p-2 border border-gray-200 rounded" rows="3" placeholder="Masukkan alamat lengkap"></textarea>
            </div>
            
            <div class="mb-6">
                <label for="delivery-notes" class="block mb-1 font-medium">Catatan Tambahan</label>
                <textarea id="delivery-notes" class="w-full p-2 border border-gray-200 rounded" rows="3" placeholder="Masukkan catatan jika ada"></textarea>
            </div>
            
            <div class="flex flex-col sm:flex-row justify-between gap-3">
                <button class="bg-gray-300 text-gray-700 py-2 px-6 rounded font-medium hover:bg-gray-400 transition-colors w-full sm:w-auto">Batalkan</button>
                <button id="confirm-delivery" class="bg-[#ff9a00] text-white py-2 px-6 rounded font-medium hover:bg-orange-600 transition-colors w-full sm:w-auto cursor-pointer">Konfirmasi Pengiriman</button>
            </div>
        </div>
    </main>
    @section('script')
    @include('script.render-cart')
    @include('script.cart-item-get')
    @include('script.order-script')
    @stop
</x-layout>